sudo: false

os: linux

dist: trusty

addons:
  browserstack:
    username: ${BROWSERSTACK_USERNAME}
    access_key:
      secure: ${BROWSERSTACK_ACCESS_KEY}

language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: test
      script: mvn clean test